### ISSUE TITLE
MySQL56u Doesn't Restart After Package Upgrade

### ISSUE THREAD

**Issue by JabuXm3** [iuscommunity-pkg/mysql56u#5]
Howdy,

My RHEL 6.8 server recently automatically updated the IUS mysql56u package to 5.6.31 and after the package was updated it was not restarted correctly. Judging based on my servers logs it appears that the MySQL restart command didn't execute properly as a result of InnoDB still shutting down when it was issued. As a result MySQL was down until a human had to intervene to get it started again.

My server had well over 30+ GB of RAM consumed alone by MySQL at that time and because of that I'm assuming a large amount of pages needed to be committed to disk which is what took so long. Furthermore, "innodb_fast_shutdown" was set to "1" as it should be per the default configuration.

The logs look as follows:

```
---
2016-04-28 04:07:48 17104 [Note] InnoDB: FTS optimize thread exiting.
2016-04-28 04:07:48 17104 [Note] InnoDB: Starting shutdown...
160428 04:08:46 mysqld_safe A mysqld process already exists
2016-04-28 04:09:45 17104 [Note] InnoDB: Shutdown completed; log sequence number 586989372344
2016-04-28 04:09:45 17104 [Note] Shutting down plugin 'CSV'
---
```

Can you please look into this when you get a chance?

Thanks,

-jLoe

**Comment by mikegriffin** [comment]
jLoe,

This init script allows an override of the default STOPTIMEOUT:

`
# Set timeouts here so they can be overridden from /etc/sysconfig/mysqld
STARTTIMEOUT=120
STOPTIMEOUT=60

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
`


To accomplish this, you could create a new file:

echo STOPTIMEOUT=600 > /etc/sysconfig/mysqld

That said, I would suggest that the IUS packagers increase the timeout to 600 by default. This should not increase restart time for most users as it is a maximum sleep not a prescribed sleep time:

# time /etc/init.d/mysqld restart
Stopping mysqld:                                           [  OK  ]
Starting mysqld:                                           [  OK  ]

real	0m1.062s
user	0m0.019s
sys	0m0.022s

# cat /etc/sysconfig/mysqld
STOPTIMEOUT=600


The larger default should help users with a large innodb_buffer_pool_size that has lots of unflushed dirty pages in the pool.

**Comment by scottgilbert** [comment]
I suggest setting the timeout using a "double greater-than", like this:

`echo STOPTIMEOUT=600 >> /etc/sysconfig/mysqld`

This will create the file if it does not exist.  But if the file does exist, this will append to it, instead of overwriting it.

I agree with increasing the default timeout value.  Especially during a server shutdown, we really want to let mysql complete a clean shutdown before we proceed with things like terminating processes and unmounting filesystems.  The timeout is only to protect us against a mysqld process which is hung and will never complete its shutdown. In this case, we do eventually want to "give up" on the mysqld shutdown and proceed, but this should be a last resort.

**Comment by carlwgeorge** [comment]
For reference, the [Fedora mariadb service file](http://pkgs.fedoraproject.org/cgit/rpms/mariadb.git/tree/mysql.service.in#n63) uses 300 seconds for both the start and stop timeout.  The IUS mariadb100u and mariadb101u have the same setting, since they were forked from the Fedora packages.

**Comment by b-harper** [comment]
I am sure whatever decision we make for mysql56u, the next question will be about making similar changes to our other MySQL and MariaDB packages.  

It is important to note that IUS stands for 'Inline with Upstream Stable'.  Upstream being the project in question (like MySQL), but generally we build from Fedora SRPMs to make sure our packages align with Fedora/EL best practices.  Generally, we do not like to drift from upstream or Fedora default configurations.  When IUS first started packaging MySQL, the defaults were very bare and not that great.  A group of trusted DBAs, provided some updated configuration files to help fill the gap.  A lot has changed, many forks have become popular and the switch to systemd have caused us to rethink the need for custom configurations.

For our MySQL packages, I think it makes sense to change the timeout in either init script or /etc/sysconfig/mysqld.  This falls inline with our custom configurations we are already providing.  With MariaDB, the upstream default are much better (than back in the day) and we are trying to realign with upstream defaults again.  In addition, systemd has a much better process for a server administrator to customize the service files provided in a package.  If we really feel that 300 seconds is not a good default, I would like us to see if we can get the change in the Fedora MariaDB packages. 

Here are timeout settings from various MySQL versions and forks:

Stock EL6 5.1 MySQL:
STARTTIMEOUT=120
STOPTIMEOUT=60

EL6 mysql57-community from mysql.com:
STARTTIMEOUT=120
STOPTIMEOUT=600

EL6 mysql56-community from mysql.com:
STARTTIMEOUT=120
STOPTIMEOUT=60

EL6 mysql55-community from mysql.com:
STARTTIMEOUT=120
STOPTIMEOUT=60

EL6 Percona-Server-server-57 from percona.com:
STARTTIMEOUT=120
STOPTIMEOUT=600

EL6 Percona-Server-server-56 from percona.com:
service_startup_timeout=900

EL6 Percona-Server-server-55 from percona.com:
service_startup_timeout=900

EL6 MariaDB-server 5.5 from mariadb.org:
service_startup_timeout=900


@mikegriffin's recommendation of 600 seems to fall inline with the greater MySQL ecosystem defaults.

**Comment by b-harper** [comment]
There has been talk about changing the timeout value in /etc/sysconfig/mysqld.  I think that is a better approach for an end user.  If we wanted to change the timeout in the package itself, I think it makes sense to update the init script.  Is there any reason for the package to include the timeout in /etc/sysconfig/mysqld?

**Comment by carlwgeorge** [comment]
I agree that it makes sense configure the default value in the init script, but it would be useful to also make note of of those values in /etc/sysconfig/mysqld with a commented out line.  It is fairly standard that commented out configuration options represent the default value.  For example, if we use 300 seconds for both the start and stop values:

* /etc/init.d/mysqld
```
STARTTIMEOUT=300
STOPTIMEOUT=300
```
* /etc/sysconfig/mysqld
```
# Edit these variables to override the default timeout values in /etc/init.d/mysqld.
#STARTTIMEOUT=300
#STOPTIMEOUT=300
```

**Comment by b-harper** [comment]
I am curious if anyone has any opinions on what the timeout values should be and if we should include a /etc/sysconfig/mysqld file.

**Comment by b-harper** [comment]
I have went ahead and created a pull request.  If we don't hear any major objections within the next few days, we will merge the pull request and start building packages.

**Comment by carlwgeorge** [comment]
While we are at it, should we go ahead and raise STARTTIMEOUT as well?

**Comment by b-harper** [comment]
Since we did not hear any negative feedback, we merged the pull request and updated packages will hit the testing repository during tonight's automation run.

**Comment by b-harper** [comment]
This fix will hit the stable repositories during tonight's automation run.  If you feel this fix is needed for our other database packages, please open an issue within the package's GitHub repository.
